spring.application.name=WhetherApplication-1


openweather.api.key=c8d7005e8b0430f099a446ee9b6471ea
openweather.api.url=https://api.openweathermap.org/data/2.5/weather

spring.cache.caffeine.spec=maximumSize=100,expireAfterWrite=10m
spring.cache.type=caffeine

